services:
    database:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
            - db-logs:/var/log/mysql
        networks:
            - app_network

    php:
        build:
            context: .
        image: php:8.4.10-fpm-alpine3.22
        container_name: php
        user: "1000:1000"
        restart: always
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        networks:
            - app_network

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app_network

    node:
        image: node:23.7.0-alpine3.20
        container_name: node
        user: "1000:1000"
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        command: sh -c "tail -f /dev/null"
        ports:
            - "5173:5173"
        networks:
            - app_network

volumes:
    db-data:
    db-logs:

networks:
    app_network:
        driver: bridge
        name: app_network
